### ISSUE TITLE
Create demo to show all the props usage

### ISSUE THREAD

**Issue by lourenci** [asseinfo/react-kanban#115]
Add demo for:

* [ ] Board without any configuration
* [ ] Board with permission to remove the lanes
* [ ] Board with permission to add new lanes
* [ ] Board with permission to remove a card
* [ ] Board with permission to rename a lane
* [ ] Board without permission to drag lanes
* [ ] Board without permission to drag cards
* [ ] Board with a custom lane header
* [ ] Board with a custom lane adder

**Comment by mathesouza** [comment]
You could break into more issues
Maybe something to control the examples progress...
What do you think?

**Comment by lourenci** [comment]
We could create tasks on this issue.

**Comment by dougfabris** [comment]
@lourenci You'll create tasks? I would like to work on that!

**Comment by lourenci** [comment]
@dougfabris, yes. I'll create the tasks as soon as possible along with the docz PR.

**Comment by deepakmountble** [comment]
do you mean demo working on code sandbox? or something else. @lourenci

**Comment by lourenci** [comment]
We don't have any idea of how to document those yet. We started off with the [docz](https://www.docz.site/) lib, but it wasn't straightforward since we've conditional props. Eg. to add a card, you have to pass two props: `allowAddCard` and 'onCardAdd`.

Do you have any idea do discuss?

Thanks.

**Comment by anuradhabharti** [comment]
@lourenci What you mean demo? I have a little bit idea about conditional props allowAddCard,onNewCardConfirm etc.but I don't have an idea about onCardAdd.

**Comment by johnking** [comment]
I am also looking for demo, examples or tutorials on how to use this component.

**Comment by lourenci** [comment]
We've to tidy our docs up, but I don't have plans to do this until #257 gets merged.

Please, go ahead if someone is willing to create those demos.
