### ISSUE TITLE
Remove the need of the callbacks

### ISSUE THREAD

**Issue by lourenci** [asseinfo/react-kanban#140]
When the user removes a lane, the board calls for the `onLaneRemove` callback whether it is informed or not.
it doesn't make sense when the user remove a lane through the custom lane header template. The developer is being forced to pass a `noop` function in these cases.
It should be optional even when the board is using the default lane header template.

The same is happening to the other callbacks:  `onLaneRename`, `onCardRemove`...

The exception is to the `onLaneNew` callback, where it must return the new lane with the new id (we have plans to change this behaviour in the future).

**Comment by haichuan0424** [comment]
Hi, I’d like to work on this issue.

**Comment by MatheusPoliCamilo** [comment]
Can i take this one?

**Comment by lourenci** [comment]
@haichuan0424, do you have plans to solve that? Can I assign this to @mathesouza?

**Comment by mathesouza** [comment]
@lourenci no, you can't

**Comment by lourenci** [comment]
Sorry, I did mean @MatheusPoliCamilo.

**Comment by deepakmountble** [comment]
hey can you tell us the difference between on lane and column in your library context? because when I go through with documentation onColumnRemove and here onLaneRemove. I am thinking to start this issue.

**Comment by Sabrinovsky** [comment]
Hi @deepakmountble, it was a mistake we made.
Check this issue, it explain what happened https://github.com/lourenci/react-kanban/issues/192

**Comment by lourenci** [comment]
@deepakmountble, There is no concept of lane anymore in the lib, we've renamed to column in the issue point out by @Sabrinovsky. If you see that in the docs, sorry for that, It's a mistype, we already have an issue to go through the docs.

**Comment by deepakmountble** [comment]
should it be resolved because you are saying you have changed the name lane to column so what should i think that **onLaneRemove** is referring to onColumnRemove because i want to solve this issue i want to be clear that  for solving this issue what should i consider because after gone through the  #192  and reading this issue again i am confusing.
can you clear again what should happen for solve this issue?? @lourenci @Sabrinovsky

**Comment by lourenci** [comment]
In the uncontrolled board, the majority of the callbacks are meant for the user to listen to and do whatever they want outside of the board scope. The lib doesn't care at all for those callbacks internally, thus they should be optional. 

For now, the lib is throwing an exception if you don't pass those callbacks. You can see in the demo code (on codesanbox) that those callbacks are being passed as `noop` functions just with the intention to not throw any error.

**Comment by deepakmountble** [comment]
hey, i am going through the code. trying to understand the what exactly is this issue. on the link of code sandbox in docs on the Github page I found something related to this issue.
onLaneRemove={console.log}
onCardRemove={console.log}
onLaneRename={console.log}
so if i am not wrong **expected behaviour** should be like 
<Board
      allowRemoveLane
      allowRenameColumn
      allowRemoveCard
      onLaneRemove
      onCardRemove
      onLaneRename
      initialBoard={board}
/> 
@lourenci @Sabrinovsky  can you check it? is there any channel to talk to authors of this repo?

**Comment by lourenci** [comment]
Hi, @deepakmountble.

> so if i am not wrong **expected behaviour** should be like
> `<Board allowRemoveLane allowRenameColumn allowRemoveCard onLaneRemove onCardRemove onLaneRename initialBoard={board} />`

Those callbacks should not be necessary, it should be:
`<Board allowRemoveLane allowRenameColumn allowRemoveCard initialBoard={board} />`

In the uncontrolled board, I think the only callbacks necessary are the `onNewColumnConfirm` if you pass the `allowAddColumn` and `onNewCardConfirm` if you pass the `allowAddCard`, since the user has to pass the new IDs.

**Comment by deepakmountble** [comment]
hey,
@lourenci  i am working on this issue.

**Comment by deepakmountble** [comment]
@lourenci  @Sabrinovsky hey guys, I have changed code and make a pull request for the same issue.
there are test cases that are failing in PR the reason for that test cases is removing three callback functions onColumnRemove onColumnRename onCardRemove. I am thinking of removing these test cases. if I am wrong please tell me what should I do next?

**Comment by MatheusPoliCamilo** [comment]
@deepakmountble I reviewed your changes, could you take a look? @lourenci can you confirm that everything was right?
