### ISSUE TITLE
Not fully compatible with CSS grid

### ISSUE THREAD

**Issue by bofeiw** [asseinfo/react-kanban#179]
Hi,

Thanks for creating this project, it is amazing!

I am building a scheduler based on this, and I am using CSS grid to style it.
And I found that if you make a particular lane wider than other lanes, you couldn't drag the card from that wide lane to some other lanes.

For example:

<img width="1177" alt="Screen Shot 2019-11-13 at 12 11 56 am" src="https://user-images.githubusercontent.com/34177142/68674751-96c08500-05aa-11ea-8069-9e6e32c35dee.png">

https://codesandbox.io/s/react-kanban-demo-mqc0r

The first lane is wider than all other lanes. And you coluld only drag the card from the top lane to the lane in the middle. Not sure what exactly is going on, but if I change its width to same as others, it works fine.

I know this is an edge case, but it would be nice if CSS grid is fully supported.

Thanks
Bofei

**Comment by bofeiw** [comment]
One temporary workaround is to add `width: fit-content` to every cards

**Comment by Sabrinovsky** [comment]
@bofeiw i'm sorry for not answering you before... Nice that you could workaround that. I also dont know what's really happening there. 

We are working on a beta version that removes styled-components and makes easier to style the board. You can check it out here: https://github.com/lourenci/react-kanban/tree/beta
In this versino you can style the whole board by yourself not importing our css, this gives you more flexibility. If you could try it and give us some feedback we'll be very grateful.

I also fixed a bug about the column height, and i think this is kind of related with the problem you're having: https://github.com/lourenci/react-kanban/pull/339
