### ISSUE TITLE
Include declaration types for projects using TypeScript

### ISSUE THREAD

**Issue by ericrdn** [asseinfo/react-kanban#257]
On use project in react typescript i am give error, why does not exists types declaration.

Is possible includes the Types in this project?

Could not find a declaration file for module '@lourenci/react-kanban'. 'C:/Projetos/kanban/node_modules/@lourenci/react-kanban/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/lourenci__react-kanban` if it exists or add a new declaration (.d.ts) file containing `declare module '@lourenci/react-kanban';`  TS7016

**Comment by mathesouza** [comment]
I'll work on it ;)

**Comment by mathesouza** [comment]
It's harder than i thought it would be :(

**Comment by MoiseScalzo** [comment]
Any progress on types?

**Comment by Sabrinovsky** [comment]
I'm sorry but i took a break from it. 
I can't solve a problem using the dnd with ts, i need to study more ts to get through it.

**Comment by luis-antonio-ac** [comment]
Any progress on types?

**Comment by Sabrinovsky** [comment]
I started it trying to migrate to typescript, i got a little frusted and kind of abandoned it.

**Comment by Sabrinovsky** [comment]
I'll be back again on the types. I tried to migrate to typescript but it was a little frustating. So typescript will wait now, i'll write the types first.

If anyone want to help with typescript, we appreciate

**Comment by lourenci** [comment]
I'm stepping up to this. :)

**Comment by lolpnon01** [comment]
Did you solve this?

**Comment by joekendal** [comment]
+1 will sponsor $$$

**Comment by oscar-gallog** [comment]
So? this never happened?
