### ISSUE TITLE
Fix the column style while renaming when there are no cards

### ISSUE THREAD

**Issue by MatheusPoliCamilo** [asseinfo/react-kanban#260]
The columns got bigger when editing their name, I solved the height on the project board in which I work and that uses this lib, but I would like to correct it in the lib itself, what do you think? I can also change the default column header to adjust the width issue if necessary.

![Captura de tela de 2020-02-13 08-35-11](https://user-images.githubusercontent.com/25781749/74430973-c0ed4180-4e3c-11ea-82d4-51c1c7581864.png)

**Comment by lourenci** [comment]
Please, go ahead.

**Comment by MatheusPoliCamilo** [comment]
@lourenci Sorry to keep you waiting, what do you think about this resolution? https://github.com/lourenci/react-kanban/pull/358
