### ISSUE TITLE
How to edit card?

### ISSUE THREAD

**Issue by iIdiomatic** [asseinfo/react-kanban#312]
Did I missed something in doc?
I found no document explaining how to edit card data, and neither proper GUI handling for same.

Is it not there at all?

**Comment by iIdiomatic** [comment]
Seems like enhancement as there is no documentation for same. I can submit pull request but there is huge problems in build

**Comment by Sabrinovsky** [comment]
We still dont suport the card edit, it would be a good feature and we appreciate if you do the PR.

Are you having trouble building the project?

**Comment by acroyear** [comment]
With a custom renderer, you can add onClick handlers in the various divs to do inline editing or launch popup editors, then commit your data to the model.  At least for a controlled board.  I'm not sure the callbacks and helpers exist for an uncontrolled one.
