### ISSUE TITLE
Build not working with dependencies - 1.1.0

### ISSUE THREAD

**Issue by iIdiomatic** [asseinfo/react-kanban#319]
I get this below error - 

> ERROR in ./assets/index.js
> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> Error: [BABEL] D:\workspace\rayi\react-kanban-1.1.0\assets\index.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "D:\\workspace\\rayi\\react-kanban-1.1.0\\node_modules\\@babel\\preset-env\\lib\\index.js")
>     at getPlugin (D:\workspace\rayi\react-kanban-1.1.0\node_modules\@babel\preset-env\lib\index.js:67:11)
>     at Array.from.map.pluginName (D:\workspace\rayi\react-kanban-1.1.0\node_modules\@babel\preset-env\lib\index.js:258:62)
>     at Array.map (<anonymous>)
>     at _default (D:\workspace\rayi\react-kanban-1.1.0\node_modules\@babel\preset-env\lib\index.js:258:43)
>     at D:\workspace\rayi\react-kanban-1.1.0\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
>     at D:\workspace\rayi\react-kanban-1.1.0\node_modules\@babel\core\lib\config\full.js:199:14
>     at Generator.next (<anonymous>)
>     at Function.<anonymous> (D:\workspace\rayi\react-kanban-1.1.0\node_modules\@babel\core\lib\gensync-utils\async.js:26:3)
>     at Generator.next (<anonymous>)
>     at step (D:\workspace\rayi\react-kanban-1.1.0\node_modules\gensync\index.js:254:32)

Though I have solved it through changing versions of few lib, but I don't understand is how a tagged build released to NPM is not working ?

**Comment by lourenci** [comment]
Hi, @iIdiomatic.

When does this error happen? On `yarn add`?
What libs do you have to change the version for?
Did you have added the `styled-component` as a dependency of your project?

This is an odd behavior since I have this version running in a production system. Including our demo on [codesandbox](https://codesandbox.io/s/5k7py44kl?fontsize=14).

**Comment by iIdiomatic** [comment]
@lourenci 

It happens on yarn start, my build platform is windows.

List of changes: (as currently I don't have access to machine that I was working on I am writing this from what I could recall)

1. I need to remove semantic-release as it doesn't work on windows. (Ideally should not break anything at-least for running).
2. I copied dependencies from your latest master branch to make it start..
3. As I thought this should be an OS specific problem I made a try on amazon linux on EC2. Problem persists.


So above were the steps that makes this library standalone workable. Till now I haven't made a talk on making it as dependency. Logs are as above.

**Problem second**
Now even if I was able to make it work after version changes from master branch. When I tried to make change in library and build it through "prepublishOnly" command. 


1. Firstly I have to make changes to command to make it work on windows, it became -  "webpack --config webpack.prod.js".  Mean I removed _rm_ command and _environment setting_ for production. I believe that impacts nothing.
2. It was built successfully in dist folder. But when I tried making it local dependency through "file://" in my project. It gave me runtime error for invalid hook call in memo-one library.
3. It was observed that the index.js file that I was creating from code from github with no changes was around 3kb more than the index.js that is been downloaded from npm.
4. To mention my main project is just core-ui project [https://github.com/coreui/coreui-react](https://github.com/coreui/coreui-react).


I ended up copying the whole source code into my main project rather than using it as library.

But again these issues to a tagged build is somewhat strange. May be a minor library difference from the time you build and I build could be a problem as you are not using exact version.

Let me know if you need any further details.

**Comment by lourenci** [comment]
Thanks for the response, @iIdiomatic.

I haven't tried to build the lib on a Windows machine, I'll try to this as soon as possible to figure out that build problems.

In a Linux machine, this is very odd. To run the e2e tests on CI we have to build it before. We don't have any problems with Linux on Github Actions nor Travis CI, both are ubuntu, I think...

**Comment by lourenci** [comment]
Are you trying to use it as a dependency? You shouldn't have any problem using it as a dependency since the lib and its dependencies are bundled all the way.

**Comment by iIdiomatic** [comment]
Yes it don't have any issue if I directly use it from npm. But when I try to build from source it ends up in error of memo-one, in the bundle only. 

I set optimize:false for bundler to debug as source code, from where I got to know on memo-one creating issue which in-turn throws error invalid react-hook call.

 I believe there is some minor version mismatch that creating this issue, as you not using fixed version. Let me know if more info needed.

**Comment by Sabrinovsky** [comment]
@iIdiomatic if i clone your project https://github.com/coreui/coreui-react and try to install this lib, the error should pops up?

I can do some tests here

**Comment by iIdiomatic** [comment]
That's so nice, yes please download source code of 1.1.0 and build it. Please use it as local dependency through "file://" to reproduce issue. As I mentioned, direct inclusion from NPM is working.

**Comment by Sabrinovsky** [comment]
@iIdiomatic I download it, added the kanban locally and them npm start. The demo project worked just fine, but i cant import the package:  Can't resolve '@lourenci/react-kanban' in...
I dont know why this error since the project was installed and validated by npm install.
I dont know what else we can do :/
