### ISSUE TITLE
add something below all cards in column

### ISSUE THREAD

**Issue by krzysztofsaw** [asseinfo/react-kanban#332]
I think it would be a good idea to add something like "bottom header". For example, I want to add a button to add a new card or some information

**Comment by Sabrinovsky** [comment]
Hi @krzysztofsaw
You mean something like the custom column header we got, but on the bottom side of the column?

https://github.com/lourenci/react-kanban#rendercolumnheader

**Comment by krzysztofsaw** [comment]
Yes, for example, I want to add a button, or icons below all the card in column, on the bottom side of the column

**Comment by lourenci** [comment]
I think it's a good idea. I'll add this to the road map.

Thanks.

**Comment by anuradhabharti** [comment]
@lourenci I am working on this issue.

**Comment by thetwosents** [comment]
Definitely. CRMs use that a lot for totals and adding.
