### ISSUE TITLE
cardRemove issues

### ISSUE THREAD

**Issue by MilesHart** [asseinfo/react-kanban#341]
I've create an end column as a "delete" column to drag cards to.

The "delete" column has a id of 9999 and in the move event I'm capturing this.

I'm supplying the board, source column (as it hasn't completed the card move) and card object, I'm getting errors.

Uncaught TypeError: Cannot read property 'cards' of undefined

Any ideas?

**Comment by MilesHart** [comment]
`function handleCardMove (_card, source, destination){
		if (destination.toColumnId === 9999){
			debugger;
			let blah = removeCard(testBoard, source, _card);
			//let updatedBoard2 = removeCard(testBoard, destination, _card)
			//postRemoveCard(_card);
			//setBoard(updatedBoard2);
		}
		else{
			const updatedBoard = moveCard(testBoard, source, destination);
			setBoard(updatedBoard);
			postMoveCard(_card, destination);
		}
	}`

**Comment by Sabrinovsky** [comment]
@MilesHart can you reproduce this on codesandbox?

**Comment by MilesHart** [comment]
I'm a bit new to react so not 100% on how. If you let me know how to build a dev version of this repo, I can use that and hopefully debug this a little easier?

**Comment by MilesHart** [comment]
As a bit of context, I have a board with a custom render.

```
<Board
	onCardDragEnd = { handleCardMove }
	renderCard={({ content }, { removeCard, dragging }) => {
	return (
		<YourCard
			isupdating={cardUpdating}
			dragging={dragging}
			heading={content.heading}
			body={content.body}>
			{content}
		</YourCard>
		);
	}}>
	{testBoard}
</Board>
```

I have a column far right "Delete", which I use for user to drag cards to so they get deleted.

```
function handleCardMove (_card, source, destination){
	if (destination.toColumnId === 9999){
		
		let blah = removeCard(testBoard, source, _card);
		
	}
	else{
		const updatedBoard = moveCard(testBoard, source, destination);
		setBoard(updatedBoard);
		postMoveCard(_card, destination);
	}
}
```
The move to a regular column works fine, however the move to 9999 fails in a TypeError: Cannot read property 'cards' of undefined

**Comment by lourenci** [comment]
> I'm a bit new to react so not 100% on how. If you let me know how to build a dev version of this repo, I can use that and hopefully debug this a little easier?

Hi, @MilesHart. Thank you for reaching out.

Sorry for that, but can you use this [codesandbox](https://codesandbox.io/s/5k7py44kl?fontsize=14) to try to reproduce your problem? It's hard to understand what is going on without a demo.
