### ISSUE TITLE
Allow Conditional Dropping

### ISSUE THREAD

**Issue by mkmanuel** [asseinfo/react-kanban#395]
Hi all,

react-beautiful-dnd allows conditional dropping based on the prop _type_. This could be easily added to react-kanban as well, such that a type prop can be added to each card and each column. Only Draggables of the same type as the Droppable will work, if the type does not match, then the drop will be cancelled.

this can be used e.g. for: 
- have a board with "todo", "in progress", "done".
- a card can only be moved one column, e.g. from todo to in progess, but not directly to done.

Reference to react-beautiful-dnd: https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md#conditionally-dropping

I'm willing to try to implement this, if you want, but I think I'm not familiar enough with react-beautiful-dnd to get it done quickly.

Sidenote: In the npm repository, this package is already minified. This is not useful imho, as this will happen anyways when any app is built. Because of this, I always go through the Github repo instead of accessing the files in my IDE.

**Comment by mkmanuel** [comment]
I implemented this locally, it only needs the new prop type={columnType} in file /Board/components/Column/index.js on line 45.

`            <DroppableColumn droppableId={String(children.id)} type={columnType}>
`
When a card is moved, it can only be dropped in a column with the same _type_ as the column it originated in.

**Comment by mkmanuel** [comment]
https://github.com/mkmanuel/react-kanban/tree/allow-cond-dropping

I've yet to implement tests etc., but for controlled boards this simple implementation works perfectly

**Comment by lourenci** [comment]
Hi, @mkmanuel. Sorry for the delay.

I can't see how the API is going to work. I'll wait for the specs to look into your implementation.
It's important that your PR closes #351 and #289, those are our needs for today.

> Sidenote: In the npm repository, this package is already minified. This is not useful imho, as this will happen anyways when any app is built. Because of this, I always go through the Github repo instead of accessing the files in my IDE.

Is this true for other package bundlers besides `webpack`? If so, you have got a point.
