### ISSUE TITLE
Does  board have a simple onClick callback for each card? 

### ISSUE THREAD

**Issue by nilabh** [asseinfo/react-kanban#397]
Any way to achieve click on cards?  Is renderCard the only way?

**Comment by lourenci** [comment]
Hi, @nilabh. Sorry for the delay.

For the time being, you can just add handlers to the card through the `renderCard` prop.

Is there some specific use case you don't want to use it?

Thanks.

**Comment by nilabh** [comment]
Thanks for the quick revert @lourenci . I'm new to react and this library was quite helpful but somehow renderCard prop is not working for me as expected .. do we have an example of a simple renderCard implementation apart from the part which has to be done in the board component.

**Comment by lourenci** [comment]
Do you want to make a codesandbox with your code? You can start from [here](https://codesandbox.io/s/react-kanban-demo-nvjp3). I think I can help you out...

**Comment by idahopotato1** [comment]
Let's say I add "value" as an attribute to the card 

Like the card 1 , 2, 3 here https://codesandbox.io/s/react-kanban-demo-mzjjg

Then, is there anyway to 
1. display the value in the card 
2. sum up the value of all the cards inside that board 
3. update the sum(value) when we move the card or add new card to the board. 

Thank you

**Comment by lourenci** [comment]
Yes, you can use the `renderColumnHeader` callback, though you can only display those data on the column header. It'll receive all the cards of that column, just sum all of them up.

**Comment by lourenci** [comment]
As for the card, to customize the way you want, you need to use the `renderCard` callback.

**Comment by iamafasha** [comment]
If I use the renderCard, how do I get the column id in the custom card component?

**Comment by GusMartins499** [comment]
> If I use the renderCard, how do I get the column id in the custom card component?

I want get the column id as well
