### ISSUE TITLE
Allow custom cardAdder

### ISSUE THREAD

**Issue by visimo-pranav** [asseinfo/react-kanban#401]
Thank you people for providing this library.  I think this can be made even better by having the functionality to have custom cardAdder. This cardAdder can be passed as a props similar to renderCard prop.

**Comment by lourenci** [comment]
Hi, @visimo-pranav. Thanks for the issue.

Would you like to give it a try?

**Comment by visimo-pranav** [comment]
Sure. I will make new PR when I am done! Awesome work by the way @lourenci  and thanks for replying quickly!
