### ISSUE TITLE
Columns with different react-kanban-column colors

### ISSUE THREAD

**Issue by yafim** [asseinfo/react-kanban#404]
Hi,
Any way to render a column with custom background color without overriding react-kanban-column css property?

Something like renderColumnHeader but for the entire frame of the column.

**Comment by Sabrinovsky** [comment]
We dont have any way to do it now. But it may be a good feature, what do you think @lourenci

**Comment by gbonaspetti** [comment]
Hi, we use react-kanban on [tracim](https://github.com/tracim/tracim) and we also miss this feature, so I just wanted to leave an "up" comment to increase its priority :smiley:.
