### ISSUE TITLE
why Rendered Card moveCard function only works for last card?

### ISSUE THREAD

**Issue by NaudyDev** [asseinfo/react-kanban#424]
I am adding dynamic data on on custom card using render card but when i drag first some cards they doesnt work it only moving the last card and the content object also storing the last card data which is something strange for me...

**Comment by lourenci** [comment]
Do you mind setting an example based on [the demo](https://codesandbox.io/s/react-kanban-demo-nvjp3)?

**Comment by NaudyDev** [comment]
I am inserting data in boards cards array and when it the data been set in the board and when i try to move the card its picking the last data been added into the cards array no matter which colums card its been add.
.... 
and ill try to make one example...

**Comment by NaudyDev** [comment]
> Do you mind setting an example based on [the demo](https://codesandbox.io/s/react-kanban-demo-nvjp3)?

I am inserting data in boards cards array and when it the data been set in the board and when i try to move the card its picking the last data been added into the cards array no matter which columns card its been add.
....
and ill try to make one example... but can you check the moveCard() function by just adding the dynamic data in the board...

**Comment by NaudyDev** [comment]
i have another question to ask to can i limit the height of the columns bcs when the data get increased columns gets stretched with it and it doesn't look good to scroll on it?
