### ISSUE TITLE
Rendering too many cards hits the performance

### ISSUE THREAD

**Issue by viganzeqiri** [asseinfo/react-kanban#431]
We have used this library in the company I work, and we had the case were there were more than 2k cards, and without virtualization the performance was broken. So I have created a PR that adds the ability to use virtual lists.

here is the PR, I have opened: https://github.com/lourenci/react-kanban/pull/430

**Comment by nmarchais** [comment]
I am interested in this PR. Thanks a lot! It's exactly what I need.
Any idea when I can expect a merge?

**Comment by Valentinishe** [comment]
I am interested in this PR, too))
