### ISSUE TITLE
How to wrap columns 

### ISSUE THREAD

**Issue by brunomc** [asseinfo/react-kanban#444]
How to wrap columns when overflow x?

**Comment by Kyle772** [comment]
display: flex
flex-wrap: wrap
max-width: 100%

**Comment by cmacdonnacha** [comment]
Do you mean adding a scoop container inisde a single column?

**Comment by brunomc** [comment]
When I have a lot of columns, we have a scroll bar. I don't want the scroll bar, I want it to break the line

**Comment by hgb072082** [comment]
is solved?

**Comment by quenginedev** [comment]
A column wrapper will be nice to have since I want to functionality to load more cards when I reach the end or bottom of a column
