### ISSUE TITLE
The column isn't passed to the renderCard callback

### ISSUE THREAD

**Issue by binterus** [asseinfo/react-kanban#449]
Hi, thank you for your work! This lib looks promising for me.

I ran into a problem with passing the column index to the card component. Why is the column not being passed to the renderCard callback in the case of controlled boards?

`
renderCard={(_column, card, dragging) => {
        if (renderCard) return renderCard(card, { dragging })
`

I wish I could easily obtain the column index when performing custom card removal. Currently, I've to do some finds in the board state to fill in the params of the removeCard helper function or to process some column data in the card rendering callback, any better solution for that?

**Comment by devqazi** [comment]
Yes I second that currently for editing cards I have to do a 2d lookup to modify the card. Also there is no helper function for `updateCard` but there is one for `changeColumn`

IMO this could be much cleaner if I could get the `column.id` within the `renderCard`
```
  const openDeleteCardDialog = (event) => {
    let cardId = event.currentTarget.dataset.id;
    let columnId = null;
    board.columns.forEach(col => {
      col.cards.forEach(card => {
        if (card.id === cardId) {
          columnId = col.id;
        }
      })
    });
    setDialog({
      type: 'delete-card',
      cardId,
      columnId,
    });
  }
```
