### ISSUE TITLE
Move inline css to style.css

### ISSUE THREAD

**Issue by nicosh** [asseinfo/react-kanban#453]
I think move [inline css ](https://github.com/asseinfo/react-kanban/blob/fee96a4b6699b327b6622b752c06ce6411977262/src/components/Board/components/Column/index.js#L33) to style.css would make the library more flexible and customizable.  
At the moment is really hard to make the board responsive (ex. use flex layout), especially when wrapped in other sections.   
There is any particular reason for those bunch of inline css to exists?  
If you want i can submit a PR.

**Comment by lourenci** [comment]
There is no reason for that. We appreciate PRs solving css issues. Thanks.

@asseinfo/asseinfo, I think we should make a regression test to avoid problems with css changes.
