### ISSUE TITLE
How can include new faces card? 

### ISSUE THREAD

**Issue by pavenkostanislav** [asseinfo/react-kanban#457]
Hi! Guies!

I create special status-board.
For my task new use card something like this https://v3.material-ui.com/demos/grid-list/#grid-list-with-titlebars

How can I include my component into your card face?

Thank you in advance for your help.

**Comment by Sabrinovsky** [comment]
You mean a custom styled card? if is it, you can use the [renderCard](https://github.com/asseinfo/react-kanban#rendercard)
