### ISSUE TITLE
Can't find @types

### ISSUE THREAD

**Issue by gabrielgstein-dev** [asseinfo/react-kanban#462]
Hi!
I'm trying use typescript with it. But when i try install refered type lib "npm i --save-dev @types/asseinfo__react-kanban". Gave me 404 error, not founding the @types pack

![image](https://user-images.githubusercontent.com/9320910/139477998-8aca9c89-9559-4558-ba9d-15030e793f47.png)

**Comment by permmy** [comment]
I also need help in this.

**Comment by matheuscamarques** [comment]
i need help

**Comment by maximelebastard** [comment]
Hello guys, this is because the types don't exist (yet).
Until you or someone else provides them, you can just ignore the typing using ts-ignore:
```
// @ts-ignore
import Board from '@asseinfo/react-kanban';
```
