### ISSUE TITLE
Not Working on React 18

### ISSUE THREAD

**Issue by brenfreeze** [asseinfo/react-kanban#476]
I tried using it on our nextjs project that has react v18.2.0. Drag is not working.

[Here's a codesandbox link replicating the issue](https://codesandbox.io/s/intelligent-allen-pwcvk8?file=/src/index.js)

**Comment by alexchantastic** [comment]
It should work if if you remove `StrictMode`. Not ideal, but a quick fix until React 18 compatibility is added.
